"""school and role columns to user model

Revision ID: 1d6d7386b5c3
Revises: 5575f96d54b4
Create Date: 2018-04-15 12:14:02.858452

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1d6d7386b5c3'
down_revision = '5575f96d54b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'role', sa.String(length=60), nullable=True))
    op.add_column('user',
                  sa.Column('school', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'school')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
